import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useAccount, useChainId, useBalance } from 'wagmi';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  // Get the connected wallet's address
  const { address } = useAccount();
  // Get the current chain ID
  const chainId = useChainId();



  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton chainStatus="name" />
        <p>A => {address ? address : 'Not connected'}</p>

        <p>C => {chainId ? chainId : 'Not connected'}</p>
      </main>
    </div>
  );
};

export default Home;
